use_frameworks!

platform :ios, '8.0'

target 'PoporFFmpegTool_Example' do
  pod 'PoporFFmpegTool', :path => '../'

  #pod 'mobile-ffmpeg-full', '3.1'
  
  target 'PoporFFmpegTool_Tests' do
    inherit! :search_paths

    
  end
end
